// Code generated by protoc-gen-go. DO NOT EDIT.
// source: command.proto

package messages

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Command_Cmd int32

const (
	Command_None Command_Cmd = 0
	Command_Shot Command_Cmd = 1
)

var Command_Cmd_name = map[int32]string{
	0: "None",
	1: "Shot",
}

var Command_Cmd_value = map[string]int32{
	"None": 0,
	"Shot": 1,
}

func (x Command_Cmd) String() string {
	return proto.EnumName(Command_Cmd_name, int32(x))
}

func (Command_Cmd) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_213c0bb044472049, []int{0, 0}
}

type Command struct {
	Time int64 `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	// y velocity
	Yv float64 `protobuf:"fixed64,2,opt,name=yv,proto3" json:"yv,omitempty"`
	// x velocity
	Xv float64 `protobuf:"fixed64,3,opt,name=xv,proto3" json:"xv,omitempty"`
	// cmd
	Cmd                  Command_Cmd `protobuf:"varint,4,opt,name=cmd,proto3,enum=messages.Command_Cmd" json:"cmd,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Command) Reset()         { *m = Command{} }
func (m *Command) String() string { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()    {}
func (*Command) Descriptor() ([]byte, []int) {
	return fileDescriptor_213c0bb044472049, []int{0}
}

func (m *Command) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Command.Unmarshal(m, b)
}
func (m *Command) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Command.Marshal(b, m, deterministic)
}
func (m *Command) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Command.Merge(m, src)
}
func (m *Command) XXX_Size() int {
	return xxx_messageInfo_Command.Size(m)
}
func (m *Command) XXX_DiscardUnknown() {
	xxx_messageInfo_Command.DiscardUnknown(m)
}

var xxx_messageInfo_Command proto.InternalMessageInfo

func (m *Command) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *Command) GetYv() float64 {
	if m != nil {
		return m.Yv
	}
	return 0
}

func (m *Command) GetXv() float64 {
	if m != nil {
		return m.Xv
	}
	return 0
}

func (m *Command) GetCmd() Command_Cmd {
	if m != nil {
		return m.Cmd
	}
	return Command_None
}

func init() {
	proto.RegisterEnum("messages.Command_Cmd", Command_Cmd_name, Command_Cmd_value)
	proto.RegisterType((*Command)(nil), "messages.Command")
}

func init() { proto.RegisterFile("command.proto", fileDescriptor_213c0bb044472049) }

var fileDescriptor_213c0bb044472049 = []byte{
	// 157 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0xce, 0xcf, 0xcd,
	0x4d, 0xcc, 0x4b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0xc8, 0x4d, 0x2d, 0x2e, 0x4e,
	0x4c, 0x4f, 0x2d, 0x56, 0x6a, 0x64, 0xe4, 0x62, 0x77, 0x86, 0xc8, 0x09, 0x09, 0x71, 0xb1, 0x94,
	0x64, 0xe6, 0xa6, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x30, 0x07, 0x81, 0xd9, 0x42, 0x7c, 0x5c, 0x4c,
	0x95, 0x65, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0x8c, 0x41, 0x4c, 0x95, 0x65, 0x20, 0x7e, 0x45, 0x99,
	0x04, 0x33, 0x84, 0x5f, 0x51, 0x26, 0xa4, 0xce, 0xc5, 0x9c, 0x9c, 0x9b, 0x22, 0xc1, 0xa2, 0xc0,
	0xa8, 0xc1, 0x67, 0x24, 0xaa, 0x07, 0x33, 0x57, 0x0f, 0x6a, 0xa6, 0x9e, 0x73, 0x6e, 0x4a, 0x10,
	0x48, 0x85, 0x92, 0x24, 0x17, 0xb3, 0x73, 0x6e, 0x8a, 0x10, 0x07, 0x17, 0x8b, 0x5f, 0x7e, 0x5e,
	0xaa, 0x00, 0x03, 0x88, 0x15, 0x9c, 0x91, 0x5f, 0x22, 0xc0, 0x98, 0xc4, 0x06, 0x76, 0x94, 0x31,
	0x20, 0x00, 0x00, 0xff, 0xff, 0xf8, 0x17, 0x90, 0xb5, 0xa5, 0x00, 0x00, 0x00,
}
