// Code generated by protoc-gen-go. DO NOT EDIT.
// source: data.proto

package messages

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Data struct {
	Y float64 `protobuf:"fixed64,1,opt,name=y,proto3" json:"y,omitempty"`
	X float64 `protobuf:"fixed64,2,opt,name=x,proto3" json:"x,omitempty"`
	// y velocity
	Yv float64 `protobuf:"fixed64,3,opt,name=yv,proto3" json:"yv,omitempty"`
	// x velocity
	Xv                   float64  `protobuf:"fixed64,4,opt,name=xv,proto3" json:"xv,omitempty"`
	Height               int64    `protobuf:"varint,5,opt,name=height,proto3" json:"height,omitempty"`
	Width                int64    `protobuf:"varint,6,opt,name=width,proto3" json:"width,omitempty"`
	Color                string   `protobuf:"bytes,7,opt,name=color,proto3" json:"color,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}
func (*Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{0}
}

func (m *Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Data.Unmarshal(m, b)
}
func (m *Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Data.Marshal(b, m, deterministic)
}
func (m *Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data.Merge(m, src)
}
func (m *Data) XXX_Size() int {
	return xxx_messageInfo_Data.Size(m)
}
func (m *Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Data proto.InternalMessageInfo

func (m *Data) GetY() float64 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Data) GetX() float64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Data) GetYv() float64 {
	if m != nil {
		return m.Yv
	}
	return 0
}

func (m *Data) GetXv() float64 {
	if m != nil {
		return m.Xv
	}
	return 0
}

func (m *Data) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Data) GetWidth() int64 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *Data) GetColor() string {
	if m != nil {
		return m.Color
	}
	return ""
}

func init() {
	proto.RegisterType((*Data)(nil), "messages.Data")
}

func init() { proto.RegisterFile("data.proto", fileDescriptor_871986018790d2fd) }

var fileDescriptor_871986018790d2fd = []byte{
	// 151 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x2c, 0xce, 0x4f, 0x0a, 0x02, 0x21,
	0x14, 0x80, 0x71, 0xde, 0xfc, 0xb1, 0x7a, 0x44, 0x0b, 0x89, 0x78, 0x4b, 0x69, 0xe5, 0xaa, 0x4d,
	0x57, 0xe8, 0x04, 0xde, 0xc0, 0x1a, 0x19, 0x07, 0x0a, 0x63, 0x14, 0xd3, 0x0b, 0x74, 0xee, 0x50,
	0x5b, 0xfe, 0xbe, 0xd5, 0x87, 0x38, 0xe9, 0xa0, 0x2f, 0xef, 0xd5, 0x05, 0xc7, 0xb7, 0x2f, 0xe3,
	0xbd, 0x9e, 0x8d, 0x3f, 0x7f, 0x01, 0x87, 0x9b, 0x0e, 0x9a, 0xef, 0x11, 0x32, 0x81, 0x00, 0x09,
	0x0a, 0x72, 0x51, 0xa2, 0xae, 0x29, 0xf1, 0x03, 0x76, 0x39, 0x52, 0x5f, 0xd9, 0xe5, 0x58, 0x9c,
	0x22, 0x0d, 0xcd, 0x29, 0xf2, 0x13, 0x32, 0x6b, 0x96, 0xd9, 0x06, 0x1a, 0x05, 0xc8, 0x5e, 0xfd,
	0xc5, 0x8f, 0x38, 0x7e, 0x96, 0x29, 0x58, 0x62, 0x35, 0x37, 0x94, 0xfa, 0x70, 0x4f, 0xb7, 0xd2,
	0x46, 0x80, 0xdc, 0xa9, 0x86, 0x3b, 0xab, 0x67, 0xd7, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa7,
	0x48, 0xbf, 0x5f, 0xa7, 0x00, 0x00, 0x00,
}
