// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package messages

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message_Type int32

const (
	Message_UNKNOWN   Message_Type = 0
	Message_HELLO     Message_Type = 1
	Message_AUTH      Message_Type = 2
	Message_JOIN      Message_Type = 3
	Message_QUIT      Message_Type = 4
	Message_DATA      Message_Type = 5
	Message_JOINED    Message_Type = 6
	Message_DIRECTION Message_Type = 7
	Message_COMMAND   Message_Type = 8
	Message_INFO      Message_Type = 9
)

var Message_Type_name = map[int32]string{
	0: "UNKNOWN",
	1: "HELLO",
	2: "AUTH",
	3: "JOIN",
	4: "QUIT",
	5: "DATA",
	6: "JOINED",
	7: "DIRECTION",
	8: "COMMAND",
	9: "INFO",
}

var Message_Type_value = map[string]int32{
	"UNKNOWN":   0,
	"HELLO":     1,
	"AUTH":      2,
	"JOIN":      3,
	"QUIT":      4,
	"DATA":      5,
	"JOINED":    6,
	"DIRECTION": 7,
	"COMMAND":   8,
	"INFO":      9,
}

func (x Message_Type) String() string {
	return proto.EnumName(Message_Type_name, int32(x))
}

func (Message_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0, 0}
}

type Message struct {
	Type                 Message_Type `protobuf:"varint,1,opt,name=type,proto3,enum=messages.Message_Type" json:"type,omitempty"`
	Data                 []byte       `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	PlayerId             int32        `protobuf:"varint,3,opt,name=playerId,proto3" json:"playerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetType() Message_Type {
	if m != nil {
		return m.Type
	}
	return Message_UNKNOWN
}

func (m *Message) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Message) GetPlayerId() int32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func init() {
	proto.RegisterEnum("messages.Message_Type", Message_Type_name, Message_Type_value)
	proto.RegisterType((*Message)(nil), "messages.Message")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 226 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x8f, 0xcd, 0x4a, 0xc4, 0x30,
	0x14, 0x46, 0xcd, 0x4c, 0xfa, 0x77, 0x75, 0xe4, 0x72, 0x17, 0x52, 0x5c, 0x95, 0x59, 0x15, 0x17,
	0x5d, 0xe8, 0x13, 0x94, 0x69, 0x65, 0xa2, 0xd3, 0x04, 0x43, 0x8a, 0xeb, 0xc8, 0x04, 0x37, 0xca,
	0x84, 0x69, 0x17, 0xf6, 0x69, 0x7d, 0x15, 0x49, 0xad, 0xee, 0xce, 0x21, 0xe7, 0x0b, 0x5c, 0xd8,
	0x7c, 0xba, 0x61, 0xb0, 0xef, 0xae, 0xf2, 0xe7, 0xd3, 0x78, 0xa2, 0x74, 0xd1, 0x61, 0xfb, 0xcd,
	0x20, 0xe9, 0x7e, 0x85, 0xee, 0x80, 0x8f, 0x93, 0x77, 0x39, 0x2b, 0x58, 0x79, 0x7d, 0x7f, 0x53,
	0xfd, 0x45, 0xd5, 0x12, 0x54, 0x66, 0xf2, 0x4e, 0xcf, 0x0d, 0x11, 0xf0, 0xa3, 0x1d, 0x6d, 0xbe,
	0x2a, 0x58, 0x79, 0xa5, 0x67, 0xa6, 0x5b, 0x48, 0xfd, 0x87, 0x9d, 0xdc, 0x59, 0x1c, 0xf3, 0x75,
	0xc1, 0xca, 0x48, 0xff, 0xfb, 0xf6, 0x0b, 0x78, 0x58, 0xd3, 0x25, 0x24, 0xbd, 0x7c, 0x96, 0xea,
	0x55, 0xe2, 0x05, 0x65, 0x10, 0xed, 0xdb, 0xc3, 0x41, 0x21, 0xa3, 0x14, 0x78, 0xdd, 0x9b, 0x3d,
	0xae, 0x02, 0x3d, 0x29, 0x21, 0x71, 0x1d, 0xe8, 0xa5, 0x17, 0x06, 0x79, 0xa0, 0xa6, 0x36, 0x35,
	0x46, 0x04, 0x10, 0x87, 0xd7, 0xb6, 0xc1, 0x98, 0x36, 0x90, 0x35, 0x42, 0xb7, 0x3b, 0x23, 0x94,
	0xc4, 0x24, 0x7c, 0xbd, 0x53, 0x5d, 0x57, 0xcb, 0x06, 0xd3, 0xb0, 0x10, 0xf2, 0x51, 0x61, 0xf6,
	0x16, 0xcf, 0x27, 0x3f, 0xfc, 0x04, 0x00, 0x00, 0xff, 0xff, 0x3f, 0x5f, 0x67, 0x07, 0x03, 0x01,
	0x00, 0x00,
}
