// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package messages

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message_Type int32

const (
	Message_UNKNOWN Message_Type = 0
	Message_HELLO   Message_Type = 1
	Message_AUTH    Message_Type = 2
	Message_JOIN    Message_Type = 3
	Message_QUIT    Message_Type = 4
	Message_DATA    Message_Type = 5
)

var Message_Type_name = map[int32]string{
	0: "UNKNOWN",
	1: "HELLO",
	2: "AUTH",
	3: "JOIN",
	4: "QUIT",
	5: "DATA",
}

var Message_Type_value = map[string]int32{
	"UNKNOWN": 0,
	"HELLO":   1,
	"AUTH":    2,
	"JOIN":    3,
	"QUIT":    4,
	"DATA":    5,
}

func (x Message_Type) String() string {
	return proto.EnumName(Message_Type_name, int32(x))
}

func (Message_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0, 0}
}

type Message struct {
	Type                 Message_Type `protobuf:"varint,1,opt,name=type,proto3,enum=messages.Message_Type" json:"type,omitempty"`
	Data                 []byte       `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	PlayerId             int32        `protobuf:"varint,3,opt,name=playerId,proto3" json:"playerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetType() Message_Type {
	if m != nil {
		return m.Type
	}
	return Message_UNKNOWN
}

func (m *Message) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Message) GetPlayerId() int32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

type Data struct {
	Y                    int32    `protobuf:"varint,1,opt,name=y,proto3" json:"y,omitempty"`
	X                    int32    `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Height               int32    `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Width                int32    `protobuf:"varint,4,opt,name=width,proto3" json:"width,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}
func (*Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Data.Unmarshal(m, b)
}
func (m *Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Data.Marshal(b, m, deterministic)
}
func (m *Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data.Merge(m, src)
}
func (m *Data) XXX_Size() int {
	return xxx_messageInfo_Data.Size(m)
}
func (m *Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Data proto.InternalMessageInfo

func (m *Data) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Data) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Data) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Data) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func init() {
	proto.RegisterEnum("messages.Message_Type", Message_Type_name, Message_Type_value)
	proto.RegisterType((*Message)(nil), "messages.Message")
	proto.RegisterType((*Data)(nil), "messages.Data")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 238 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x90, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x9d, 0x76, 0xb7, 0x8d, 0x63, 0x95, 0x65, 0x90, 0x12, 0x3c, 0x85, 0x9c, 0x82, 0x87,
	0x1c, 0xf4, 0x09, 0x02, 0x55, 0x1a, 0xad, 0x89, 0x2e, 0x09, 0x9e, 0x23, 0x59, 0x9a, 0x82, 0xd2,
	0xa5, 0x59, 0xb0, 0xfb, 0x50, 0xbe, 0xa3, 0xec, 0x76, 0xf5, 0xf6, 0x7d, 0xc3, 0x3f, 0xcc, 0xcf,
	0xe0, 0xe5, 0x97, 0x1a, 0xc7, 0x6e, 0xab, 0x72, 0x7d, 0xd8, 0x9b, 0x3d, 0x45, 0x41, 0xc7, 0xf4,
	0x07, 0x70, 0xfe, 0x72, 0x12, 0xba, 0x45, 0x66, 0xac, 0x56, 0x31, 0x24, 0x90, 0x5d, 0xdd, 0x2d,
	0xf3, 0xbf, 0x50, 0x1e, 0x02, 0x79, 0x63, 0xb5, 0x92, 0x3e, 0x43, 0x84, 0xac, 0xef, 0x4c, 0x17,
	0x4f, 0x12, 0xc8, 0x16, 0xd2, 0x33, 0xdd, 0x60, 0xa4, 0x3f, 0x3b, 0xab, 0x0e, 0x65, 0x1f, 0x4f,
	0x13, 0xc8, 0xb8, 0xfc, 0xf7, 0xf4, 0x11, 0x99, 0xdb, 0xa6, 0x0b, 0x9c, 0xb7, 0xd5, 0x73, 0x55,
	0xbf, 0x57, 0xe2, 0x8c, 0xce, 0x91, 0xaf, 0x1f, 0x36, 0x9b, 0x5a, 0x00, 0x45, 0xc8, 0x8a, 0xb6,
	0x59, 0x8b, 0x89, 0xa3, 0xa7, 0xba, 0xac, 0xc4, 0xd4, 0xd1, 0x5b, 0x5b, 0x36, 0x82, 0x39, 0x5a,
	0x15, 0x4d, 0x21, 0x78, 0xfa, 0x8a, 0x6c, 0xe5, 0x6e, 0x2d, 0x10, 0xac, 0x2f, 0xca, 0x25, 0x58,
	0x67, 0x47, 0x5f, 0x85, 0x4b, 0x38, 0xd2, 0x12, 0x67, 0x83, 0xda, 0x6d, 0x07, 0x13, 0x5a, 0x04,
	0xa3, 0x6b, 0xe4, 0xdf, 0xbb, 0xde, 0x0c, 0x31, 0xf3, 0xe3, 0x93, 0x7c, 0xcc, 0xfc, 0x4b, 0xee,
	0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xc5, 0x27, 0xa8, 0x02, 0x23, 0x01, 0x00, 0x00,
}
